version: "3"

services:
  # postgres:
  #   container_name: planify-db
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   networks:
  #     palnify-network:
  #       ipv4_address: 172.25.0.2

  #   volumes:
  #     - ./migrations/:/migrations/
  #     - ./scripts/db.sh:/db.sh

  # redis:
  #   container_name: planify-redis
  #   image: redis/redis-stack
  #   ports:
  #     - "6379:6379"
  #     - "8001:8001"
  #   networks:
  #     palnify-network:
  #       ipv4_address: 172.25.0.3

  auth:
    container_name: planify-auth
    image: mosta1489/auth:latest
    # build: ./auth-service
    ports:
      - "3000:3000"
      - "5000:5000"

    volumes:
      - ./.env:/auth/.env

    networks:
      palnify-network:
        ipv4_address: 172.25.0.4

  payment:
    container_name: planify-payment
    image: mosta1489/payment
    # build: ./payment-service
    ports:
      - "3001:3001"
    depends_on:
      - auth

    volumes:
      - ./.env:/payment/.env

    networks:
      palnify-network:
        ipv4_address: 172.25.0.5

  design:
    container_name: planify-design
    image: mosta1489/design:latest
    # build: ./design-service
    ports:
      - "3002:3002"
    depends_on:
      - auth

    volumes:
      - ./.env:/design/.env

    networks:
      palnify-network:
        ipv4_address: 172.25.0.6

  ai:
    container_name: planify-ai
    image: mosta1489/ai:latest
    # build: ./ai-service
    ports:
      - "50051:50051"
    networks:
      palnify-network:
        ipv4_address: 172.25.0.7

  nginx:
    image: nginx
    container_name: planify-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - payment
      - design
    networks:
      palnify-network:
        ipv4_address: 172.25.0.8

networks:
  palnify-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/24
