version: "3"

services:
  redis:
    container_name: planify-redis
    image: redis/redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - palnify-network

  auth:
    container_name: planify-auth
    image: auth
    # build: ./auth-service
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - palnify-network

  payment:
    container_name: planify-payment
    image: pay
    # build: ./payment-service
    ports:
      - "3001:3001"
    depends_on:
      - auth
    networks:
      - palnify-network

  design:
    container_name: planify-design
    image: design
    # build: ./design-service
    ports:
      - "3002:3002"
    depends_on:
      - auth
    networks:
      - palnify-network

  nginx:
    image: nginx
    container_name: planify-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - payment
      - design
    networks:
      - palnify-network

networks:
  palnify-network:
    driver: bridge
