name: deployment

on:
  pull_request:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to server via SSH
        env:
          MACHINE_HOST: ${{ secrets.MACHINE_HOST }}
          MACHINE_USERNAME: ${{ secrets.MACHINE_USERNAME }}
          MACHINE_KEY: ${{ secrets.MACHINE_KEY }}

        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.MACHINE_HOST }}
          username: ${{ env.MACHINE_USERNAME }}
          key: ${{ env.MACHINE_KEY }}
          port: 22
          script: |
            rm -rf Planify-Backend
            git clone https://github.com/PlanifyDev/Planify-Backend.git
            cd Planify-Backend

            touch .env

            echo SALT_ROUND=${{ secrets.SALT_ROUND }} >> .env
            echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
            echo VERIFY_EMAIL=${{ secrets.VERIFY_EMAIL }} >> .env
            echo VERIFY_PASSWORD=${{ secrets.VERIFY_PASSWORD }} >> .env
            echo DATABASE_URL_LOCAL=${{ secrets.DATABASE_URL_LOCAL }} >> .env
            echo ENV_DB=${{ secrets.ENV_DB }} >> .env
            echo ENV_CACHE=${{ secrets.ENV_CACHE }} >> .env
            echo REDIS_URL_LOCAL=${{ secrets.REDIS_URL_LOCAL }} >> .env
            echo DATABASE_URL_PROD=${{ secrets.DATABASE_URL_PROD }} >> .env
            echo FRONT_END_URL=${{ secrets.FRONT_END_URL }} >> .env 

            echo PAYPAL_ID=${{ secrets.PAYPAL_ID }} >> .env 
            echo PAYPAL_SECRET=${{ secrets.PAYPAL_SECRET }} >> .env
            echo RETURN_URL=${{ secrets.RETURN_URL }} >> .env
            echo CANCEL_URL=${{ secrets.CANCEL_URL }} >> .env
            echo AUTH_GRPC_URL=${{ secrets.AUTH_GRPC_URL }} >> .env

            echo AI_GRPC_URL=${{ secrets.AI_GRPC_URL }} >> .env

            echo AUTH_LOG_PATH=${{ secrets.AUTH_LOG_PATH }} >> .env 
            echo PAY_LOG_PATH=${{ secrets.PAY_LOG_PATH }} >> .env 
            echo DESIGN_LOG_PATH=${{ secrets.DESIGN_LOG_PATH }} >> .env 


            bash ./scripts/deploy.sh
