name: design-service

on:
  push:
    branches:
      - design
    paths:
      - "design-service/**"

jobs:
  build-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.0"

      - name: Install dependencies

        run: |
          cd design-service
          npm install

      - name: Build
        run: |
          cd design-service
          npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: build-code
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/design
      DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: |
          cd design-service
          docker build -t $DOCKER_REPO:latest .
      - name: Push Docker Image
        run: |
          docker push $DOCKER_REPO:latest
