name: design-service

on:
  pull_request:
    branches:
      - prod
    paths:
      - "design-service/**"

jobs:
  build-code:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.16.0
        uses: actions/setup-node@v2
        with:
          node-version: "18.16.0"

      - name: Install dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

  docker-build:
    runs-on: ubuntu-latest
    needs: build-code
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/design-service
      DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_REPO:latest .
      - name: Push Docker Image
        run: |
          docker push $DOCKER_REPO:latest

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: docker-build

  #   strategy:
  #     matrix:
  #       host: ${{ secrets.MACHINE_HOST }}
  #       username: ${{ secrets.MACHINE_USERNAME }}
  #       key: ${{ secrets.MACHINE_KEY }}
  #   steps:
  #     - name: Connect to server via SSH

  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ matrix.host }}
  #         username: ${{ matrix.username }}
  #         key: ${{ matrix.key }}
  #         port: 22
  #         script: |
  #           cd /home/${{ matrix.username }}
  #           docker-compose down
  #           docker-compose pull
  #           docker-compose up -d

# run: |
#             cd /home/ubuntu
#             docker-compose down
#             docker-compose pull
#             docker-compose up -d
