name: Auth-service deployer

on:
  push:
    branches: [ "auth-prod" ]
  pull_request:
    branches: [ "auth-prod" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Deploy and restart web server
    - run: |
          cd auth-service
          npm i
          npm run start:prod
  
