# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Auth-service deployer

on:
  push:
    branches: [ "auth-prod" ]
  pull_request:
    branches: [ "auth-prod" ]

jobs:
  deploy:

    runs-on: self-hosted
    
    secrets: inherit
    
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: auth-service/package-lock.json
#         working-directory: '/home/ubuntu/actions-runner/_work/Planify-Backend/Planify-Backend/auth-service/'
    env:
      DATABASE_URI: ${{ secrets.DATABASE_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      VERIFY_EMAIL: ${{ secrets.VERIFY_EMAIL }}
      VERIFY_PASSWORD: ${{ secrets.VERIFY_PASSWORD }}
      SALT_ROUND: ${{ secrets.SALT_ROUND }}
      PORT: ${{ secrets.PORT }}
    - run: |
          cd auth-service
          npm i
          npm run start:prod
