name: Auth-service deployer
# when  push or pull request on auth-prod branch
on:
  push:
    branches: [ "auth-prod" ]
  pull_request:
    branches: [ "auth-prod" ]

jobs:
  deploy:
    runs-on: self-hosted
    
    # checkout and setup node 
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    # run the server
    - name: Deploy and restart web server
    - run: |
          cd auth-service
          npm i
          npm run start:prod
  
