name: design-service

on:
  push:
    branches:
      - pay
    paths:
      - "payment-service/**"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/payment:latest
      DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build Docker Image
        run: |
          cd payment-service
          docker build -t $DOCKER_REPO .
      - name: Push Docker Image
        run: |
          docker push $DOCKER_REPO
